[project]
name = "splink-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=5.30.0",
    "openai>=1.81.0",
    "openai-agents>=0.0.16",
    "psycopg2>=2.9.10",
]
